Add a new dataset
awslabs/open-data-registry pull request #1080
Opened 2021-08-20 08:32 UTC by jacky26822865

*Issue #, if available:*

*Description of changes:*
CWB opendata dataset pull requests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-31 14:19 UTC, zflamig requested changes

2021-08-31 14:19 UTC, zflamig commented on CWB_opendata
> +    ARN:
Please add the bucket ARN here

2021-08-31 14:19 UTC, zflamig commented on CWB_opendata
> +  - Description:
You can say something like "CWB data lake" for the description

2021-09-01 07:05 UTC, awsopendata commented
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 34be1cb113d4442d26439024c471151292b8ebd1
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=e1459b02-9992-438e-a47f-9d4b92edb202%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-01 07:42 UTC, awsopendata commented
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: af1a17f388a179c49807a211a25410a3efa9398a
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=a39583c1-132a-4b16-9fa1-d0c88321d4ba%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-01 08:20 UTC, zflamig approved these changes

2021-09-02 11:11 UTC, merged