Create orcasound.yaml
awslabs/open-data-registry pull request #1104
Opened 2021-09-17 16:37 UTC by prafulfillment

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-17 16:48 UTC, awsopendata commented
### AWS CodeBuild CI Report

* CodeBuild project: open-data-registry
* Commit ID: 7595c1d6dbd69e4c1845bdf432091c434484abe4
* Result: FAILED
* [Build Logs](https://onc2c36gc4.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=43e414e4-2e0d-4d25-91fe-4dc963c33d3f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*


<!--
CREATED BY GITHUB-CODEBUILD-LOGS
-->

2021-09-17 17:54 UTC, jflasher commented
Glad to see this coming back up! Let me know when you're ready for us to review.

2021-10-29 21:47 UTC, prafulfillment commented
Updated again @jflasher

2021-11-01 16:12 UTC, jflasher requested changes

2021-11-01 16:12 UTC, jflasher commented on datasets/orcasound.yaml
> +      - Title: Github for our open source projects
I think you've got this indented one level too far, if you pull it back one level, I think this should be good to go!

2021-11-03 20:10 UTC, scottveirs approved these changes

2021-11-04 18:57 UTC, prafulfillment commented
@jflasher -- should be finalized

2021-11-05 20:29 UTC, merged

2021-11-05 20:42 UTC, jflasher commented
Thanks both, now live at https://registry.opendata.aws/orcasound/

2021-11-08 20:20 UTC, prafulfillment commented
Amazing thank you for all your help!