Add files via upload
awslabs/open-data-registry pull request #1329
Opened 2022-04-25 16:39 UTC by chenxshani

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-26 14:22 UTC, jflasher requested changes
Hi @chenxshani added a few inline comments. Also, please add a ManagedBy field like in https://github.com/awslabs/open-data-registry/blob/main/datasets/airborne-object-tracking.yaml#L5. 

Those changes should get us close to being able to merge. Thanks!

2022-04-26 14:22 UTC, jflasher commented on datasets/humor-patterns.yaml
> +Tags:
@chenxshani please use approved tags from the list at https://github.com/awslabs/open-data-registry/blob/main/tags.yaml

2022-04-26 14:22 UTC, jflasher commented on datasets/humor-patterns.yaml
> +Description: Patterns used for quering Alexa traffic when creating the taxonomy described in the paper "“Alexa, Do You Want to Build a Snowman?” Characterizing Playful Requests to Conversational Agen
Please add a bit more of a description about the data here, what is it?

2022-04-26 14:22 UTC, jflasher commented on datasets/humor-patterns.yaml
> +License: There are no restrictions on the use of this data. ########## Verify
You will need to add an actual license here.

2022-04-26 14:22 UTC, jflasher commented on datasets/humor-patterns.yaml
> +    ARN: arn:aws:s3:::humor-patterns
Correct bucket name is amazon-humor-patterns

2022-04-26 14:22 UTC, jflasher commented on datasets/humor-patterns.yaml
> +    Region: us-east-1
Region should be us-west-2 I think.

2022-04-26 14:22 UTC, jflasher commented on datasets/humor-patterns.yaml
> +Name: Humor patterns
Please add a little more description to the name that'd help someone know what this data is.

2022-04-27 13:59 UTC, chenxshani commented
Addressed all comments. Please review. Thanks!

2022-04-27 14:06 UTC, jflasher requested changes
Hi @chenxshani you'll need to add `UpdateFrequency` and `Documentation` fields as well. You can see all the required fields in the table at https://github.com/awslabs/open-data-registry#how-are-datasets-added-to-the-registry.

2022-04-27 14:35 UTC, chenxshani commented
Ready? :) @jflasher

2022-04-27 14:46 UTC, merged