YAML file for the MIT Supercloud Dataset
awslabs/open-data-registry pull request #1414
Opened 2022-06-24 21:09 UTC by ssamsis

*Issue #, if available:*

*Description of changes:*
Adding YAML file for the MIT Supercloud Dataset. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-05 20:20 UTC, jflasher requested changes
Hi @ssamsis, left a few comments inline, thanks!

2022-07-05 20:20 UTC, jflasher commented on datasets/dcc.yaml
> +      URL: https://nbviewer.org/github/MIT-AI-Accelerator/MIT-Supercloud-Dataset/blob/main/notebooks/Intro-to-MIT-Supercloud-Dataset.ipynb
Looks to be an issue with this notebook.

2022-07-05 20:20 UTC, jflasher commented on datasets/dcc.yaml
> +      URL: https://nbviewer.org/github/MIT-AI-Accelerator/workload-classification/blob/main/notebooks/Generating-the-labelled-dataset.ipynb
This notebook is failing to load as well.

2022-07-05 20:20 UTC, jflasher commented on datasets/dcc.yaml
> +  - datacenter
Please add `aws-pds` as a tag as well, thanks!

2022-09-16 14:29 UTC, jflasher commented
Hi @ssamsis wanted to check back in here, thanks!

2022-10-14 15:01 UTC, ssamsis commented
The YAML file has been updated and issues with the notebooks have been resolved.

2022-10-14 17:05 UTC, jflasher commented
Hi @ssamsis, looks like https://nbviewer.org/github/MIT-AI-Accelerator/workload-classification/blob/main/notebooks/Generating-the-labelled-dataset.ipynb is still throwing an error.

2022-10-14 23:11 UTC, ssamsis commented
The notebook URLs have been update and should work now. Thank you!

2022-10-17 16:29 UTC, jflasher approved these changes

2022-10-17 16:37 UTC, jflasher commented
@ssamsis this should be good to go. It's having an issue with a conflict on the tags.yaml. I'll look to resolve that in the next dew days by starting a new, clean PR. Thanks!

2022-10-18 14:38 UTC, closed without merging