Digital Earth Pacific (DEP) Earth Observations Products Registered.
awslabs/open-data-registry pull request #2271
Opened 2024-06-13 22:48 UTC by sopac

Digital Earth Pacific (DEP) Earth Observations Products Registered.

https://www.digitalearthpacific.org

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-06-13 22:58 UTC, cstner requested changes
Please remove any tags, like "earth observations" that aren't already in the tags file here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml

2024-06-17 02:38 UTC, sopac reviewed
Requested changes implemented.

2024-06-18 15:33 UTC, cstner requested changes
Please remove any tags that aren't already in the tags file here: https://github.com/awslabs/open-data-registry/blob/main/tags.yaml

2025-02-13 01:00 UTC, alexgleith commented
I think I've removed all the tags that aren't in the tags file @cstner

2025-02-13 16:09 UTC, merged