Draft PR for GEOS-Chem input data.
awslabs/open-data-registry pull request #2299
Opened 2024-07-16 21:29 UTC by yidant

*Description of changes:*
Draft PR for GEOS-Chem input data. This PR adds geos-chem-input-data.yaml. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-24 15:59 UTC, msulprizio commented
@yidant Pull request #2301 has now been merged. Feel free to rename your file to `geoschem-input-data.yaml` and sync with the any relevant info now in https://github.com/awslabs/open-data-registry/blob/main/datasets/geoschem-nested-input-data.yaml.

2024-07-24 19:11 UTC, yidant commented
Thanks @msulprizio ! I've updated the yaml file name and its content!

2024-07-25 15:11 UTC, msulprizio requested changes
Hi @yidant. I've requested some minor changes to the geoschem-input-data.yaml file here. 

Also tagging @yantosca and @lizziel for any feedback before this is merged in.

2024-07-25 15:11 UTC, msulprizio commented on datasets/geoschem-input-data.yaml
> +    Type: S3 Bucket
Can we add `Explore` here with the link to browse the bucket or do we not have a URL yet?

See [these lines](https://github.com/awslabs/open-data-registry/blob/cbb2a2c5d38ca4be9de3a8af1401efd38c63d8da/datasets/geoschem-nested-input-data.yaml#L27C1-L28C68) for an example.

2024-07-25 15:11 UTC, msulprizio commented on datasets/geoschem-input-data.yaml
> +  Publications:
Could you add links to the GCClassic and GCHP on the cloud papers? I think it's OK that these technically used the older S3 bucket.

```
    - Title: "Enabling Immediate Access to Earth Science Models through Cloud Computing: Application to the GEOS-Chem Model"
      URL: https://doi.org/10.1175/BAMS-D-18-0243.1
      AuthorName: Jiawei Zhuang et al.
    - Title: "Enabling high-performance cloud computing for Earth science modeling on over a thousand cores: application to the GEOS-Chem atmospheric chemistry model"
      URL: https://doi.org/10.1029/2020MS002064
      AuthorName: Jiawei Zhuang et al.
```

2024-10-10 20:28 UTC, yidant commented
Thanks @msulprizio and @cstner! There're new updates made and ready for merge!

2024-10-11 00:00 UTC, merged