New coal plant dataset as part of APAD
awslabs/open-data-registry pull request #2315
Opened 2024-07-26 11:19 UTC by khizerzakir

*Issue #, if available:*

*Description of changes:*

This dataset contains new coal plant dataset as part of the APAD project. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-05 17:48 UTC, cstner requested changes
Hi Khizer:  please submit a request to join the Open Data sponsorship program: https://application.opendata.aws/ or reach out to us if you want to list but not join the sponsorship program

2024-08-07 13:29 UTC, khizerzakir commented
> This dataset contains new coal plant dataset as part of the APAD project. It is supported by AWS to use AWS resources to do analysis and build dashboard on air pollution sources in South Asia!

I have filled out the form. However, please let me know how can we get in touch with you to list the dataset as well.

2025-01-02 19:08 UTC, cstner requested changes
Changes look good but please update your branch or give us the ability to update it for you so we can merge!

2025-01-02 19:44 UTC, khizerzakir commented
> Changes look good but please update your branch or give us the ability to update it for you so we can merge!

I have updated the branch. Thank you so much. Please let me know, if you have any questions.

2025-01-02 19:46 UTC, merged

2025-01-02 19:47 UTC, cstner commented
All set!  Should be visible within the next 30 minutes