add AllTheBacteria dataset
awslabs/open-data-registry pull request #2460
Opened 2024-12-09 23:43 UTC by mbhall88

*Issue #, if available:*

NA

*Description of changes:*

I haven't included ARNs etc. as we obviously need to have our AWS account linked before we upload the data and therefore get the ARNs.

Similar with the tutorials, we will add some simple access tutorials once we have ARNs. We are also working with some folks at AWS to build a larger more involved tutorial using the large LexicMap search index for running queries against the dataset on AWS.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-13 12:47 UTC, johnlees commented
@mbhall88 some info to help complete this

ARNs:
- arn:aws:s3:::allthebacteria-assemblies
- arn:aws:s3:::allthebacteria-phylogeneticbatches
- arn:aws:s3:::allthebacteria-metadata
- arn:aws:s3:::allthebacteria-lexicmap

Regions for all are `eu-west-2`

2024-12-16 00:12 UTC, mbhall88 commented
Awesome. Thanks @johnlees. All updated

2025-02-06 20:21 UTC, berylrab commented
Hi Michael, how is this going? I think you're on the last step of preparing the data and uploading it to the buckets right? Let us know when the PR is ready for review.

2025-02-10 16:31 UTC, johnlees commented
Michael is currently on leave but we will try and progress this. We have one last file to upload to the buckets.
(We also still need to make the tutorials)

2025-04-25 09:44 UTC, iqbal-lab requested changes
I don't thiink I have the rights to edit this, but could the following website be added please?

https://allthebacteria.org/

2025-04-28 14:39 UTC, berylrab requested changes
Hi, can we add the "life sciences" tag here? Also, the build is failing because lines 41-47 are empty, those need to be removed. "Tutorials, title, URL, NotebookURL, AuthorName, AuthorURL, and Services".

2025-04-30 18:08 UTC, merged